fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: no-commit-to-branch
      name: "Don't commit to master branch"
      args: [--branch, master]
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: check-json
    - id: end-of-file-fixer
      exclude: custom_components/econnect_metronet/manifest.json
    - id: mixed-line-ending
    - id: trailing-whitespace


- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
    - id: isort
      exclude: tests/
      args: ["--profile", "black"]

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v2.0.4
  hooks:
    - id: autopep8
      exclude: tests/
      args: [--max-line-length=100, --in-place, --aggressive]

- repo: https://github.com/PyCQA/flake8
  rev: 7.1.1
  hooks:
    - id: flake8
      exclude: tests/
      args: [--max-line-length=100]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.1
  hooks:
    - id: pyupgrade

- repo: https://github.com/PyCQA/bandit
  rev: '1.8.0'
  hooks:
    - id: bandit
      args: ["-c", "pyproject.toml"]
      additional_dependencies: ["bandit[toml]"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.4
  hooks:
    - id: ruff
      exclude: tests/
      args: [--line-length=100, --fix]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.0
  hooks:
    - id: mypy
      exclude: tests/
      additional_dependencies: [types-requests]

- repo: local
  hooks:
    - id: prettier
      name: prettier
      entry: prettier
      language: system
      types: [python, json, yaml, markdown]

    - id: pytest
      name: pytest
      entry: pytest
      language: python
      types: [python]
      pass_filenames: false
      always_run: true
      additional_dependencies: [responses, pytest-mock]
