name: CI

on:
  push:
    branches-ignore:
      - master
  pull_request: ~

env:
  FORCE_COLOR: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[all]'

    - name: Run pre-commit hooks
      uses: pre-commit/action@v3.0.1
