name: Output test results

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  report:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[all]'
        
    - name: Run Tests with Coverage
      run: |
        pip install coverage pytest pytest-cov
        coverage run -m pytest --maxfail=1 --disable-warnings -q
        coverage report -m
        coverage html
        coverage xml

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Output code coverage results to GitHub step summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
