# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test multiple Python versions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  get-python-version:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.python-version.outputs.python_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read .python-version
        id: python-version
        run: |
          python_version=$(cat .python-version)
          echo "python_version=$python_version" >> "$GITHUB_OUTPUT"
          echo "Python version found: $python_version"

  test:
    runs-on: ubuntu-latest
    needs: get-python-version
    strategy:
      matrix:
        python-version: ["3.13", "3.12", "3.11"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[all]'

    - name: Run Tests with coverage
      run: |
        pytest --cov --junitxml=junit.xml -o junit_family=legacy --cov-branch --cov-report=xml

    - name: Upload test results to Codecov
      if: ${{ !cancelled() && matrix.python-version == needs.get-python-version.outputs.python-version }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload coverage reports to Codecov
      if: ${{ !cancelled() && matrix.python-version == needs.get-python-version.outputs.python-version }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
